/*
 * Copyright 2014 Guest.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.samjoey.samples;

import javax.swing.filechooser.*;
import javax.swing.*;
/**
 *
 * @author Guest
 */
public abstract class graphicalLook extends javax.swing.JFrame {

    /**
     * Creates new form graphicalLook
     */
    public graphicalLook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelParser = new javax.swing.JPanel();
        jProgressBar_Parser = new javax.swing.JProgressBar();
        jButton_OpenFile = new javax.swing.JButton();
        jTextField_PGNLocation = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_GamesList = new javax.swing.JList();
        jLabel_GamesFound = new javax.swing.JLabel();
        jPanelCalculator = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Calculator = new javax.swing.JTable();
        jButton_Calculate = new javax.swing.JButton();
        jPanelGameViewer = new javax.swing.JPanel();
        canvas_Board = new java.awt.Canvas();
        jLabel_GameID = new javax.swing.JLabel();
        jButton_Previous = new javax.swing.JButton();
        jButton_Next = new javax.swing.JButton();
        jButton_FastForward = new javax.swing.JButton();
        jButton_Rewind = new javax.swing.JButton();
        jLabel_PlyCount = new javax.swing.JLabel();
        jLabelStatusBody = new javax.swing.JLabel();
        jLabelStatusHeader = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelParser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parser", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12), new java.awt.Color(51, 0, 0))); // NOI18N

        jButton_OpenFile.setText("Open File...");
        jButton_OpenFile.setToolTipText("Load a PGN file");
        jButton_OpenFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_OpenFileMouseClicked(evt);
            }
        });
        jButton_OpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OpenFileActionPerformed(evt);
            }
        });

        jTextField_PGNLocation.setEditable(false);
        jTextField_PGNLocation.setText("No File Chosen");
        jTextField_PGNLocation.setToolTipText("");

        jScrollPane1.setViewportView(jList_GamesList);

        jLabel_GamesFound.setText("Games Found");

        javax.swing.GroupLayout jPanelParserLayout = new javax.swing.GroupLayout(jPanelParser);
        jPanelParser.setLayout(jPanelParserLayout);
        jPanelParserLayout.setHorizontalGroup(
            jPanelParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParserLayout.createSequentialGroup()
                .addGroup(jPanelParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelParserLayout.createSequentialGroup()
                        .addComponent(jButton_OpenFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_PGNLocation))
                    .addGroup(jPanelParserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar_Parser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelParserLayout.createSequentialGroup()
                                .addComponent(jLabel_GamesFound)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanelParserLayout.setVerticalGroup(
            jPanelParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelParserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelParserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_OpenFile)
                    .addComponent(jTextField_PGNLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel_GamesFound)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addComponent(jProgressBar_Parser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelCalculator.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calculator", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12), new java.awt.Color(51, 51, 0))); // NOI18N

        jTable_Calculator.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Ply", "Player", "Title 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable_Calculator);

        jButton_Calculate.setText("Calculate");

        javax.swing.GroupLayout jPanelCalculatorLayout = new javax.swing.GroupLayout(jPanelCalculator);
        jPanelCalculator.setLayout(jPanelCalculatorLayout);
        jPanelCalculatorLayout.setHorizontalGroup(
            jPanelCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalculatorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCalculatorLayout.createSequentialGroup()
                        .addComponent(jButton_Calculate)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelCalculatorLayout.setVerticalGroup(
            jPanelCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalculatorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Calculate)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelGameViewer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Game Viewer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12), new java.awt.Color(0, 51, 51))); // NOI18N

        jLabel_GameID.setText("Game ID: -1");

        jButton_Previous.setText("◄");
        jButton_Previous.setToolTipText("Previous Ply");
        jButton_Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PreviousActionPerformed(evt);
            }
        });

        jButton_Next.setText("►");
        jButton_Next.setToolTipText("Next Ply");
        jButton_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NextActionPerformed(evt);
            }
        });

        jButton_FastForward.setText("►►");
        jButton_FastForward.setToolTipText("End of Game");
        jButton_FastForward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FastForwardActionPerformed(evt);
            }
        });

        jButton_Rewind.setText("◄◄");
        jButton_Rewind.setToolTipText("Beginning of Game");

        jLabel_PlyCount.setText("Ply Count: -1");

        javax.swing.GroupLayout jPanelGameViewerLayout = new javax.swing.GroupLayout(jPanelGameViewer);
        jPanelGameViewer.setLayout(jPanelGameViewerLayout);
        jPanelGameViewerLayout.setHorizontalGroup(
            jPanelGameViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGameViewerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelGameViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGameViewerLayout.createSequentialGroup()
                        .addComponent(jLabel_GameID)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel_PlyCount))
                    .addComponent(canvas_Board, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelGameViewerLayout.createSequentialGroup()
                        .addComponent(jButton_Rewind)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Previous)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Next)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_FastForward)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanelGameViewerLayout.setVerticalGroup(
            jPanelGameViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGameViewerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGameViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_GameID)
                    .addComponent(jLabel_PlyCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canvas_Board, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGameViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Previous)
                    .addComponent(jButton_Next)
                    .addComponent(jButton_FastForward)
                    .addComponent(jButton_Rewind))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelStatusBody.setText("--");

        jLabelStatusHeader.setText("Status:");
        jLabelStatusHeader.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCalculator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelStatusHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelStatusBody, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelParser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelGameViewer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelGameViewer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelParser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanelCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatusBody)
                    .addComponent(jLabelStatusHeader)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_NextActionPerformed

    private void jButton_FastForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FastForwardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_FastForwardActionPerformed

    private void jButton_PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PreviousActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_PreviousActionPerformed

    private void jButton_OpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OpenFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_OpenFileActionPerformed

    private void jButton_OpenFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_OpenFileMouseClicked
        jLabelStatusBody.setText("Choosing a file to parse");
        
        JFileChooser fc = new JFileChooser();
        
        int returnVal = fc.showDialog(this, "Parse");
 
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                final java.io.File file = fc.getSelectedFile();
                //This is where a real application would open the file.
                jLabelStatusBody.setText("Reading " + file.getName());
                (new Thread() {
                    public void run() {
                        selectedPGN(file);
                    }
                }).start();
            }
            else {
                jLabelStatusBody.setText("Open command cancelled by user.");
            }
    }//GEN-LAST:event_jButton_OpenFileMouseClicked
    
    public void selectedPGN(java.io.File file) {
        jLabelStatusBody.setText("Done parsing");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(graphicalLook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(graphicalLook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(graphicalLook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(graphicalLook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                (new graphicalLook(){}).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected java.awt.Canvas canvas_Board;
    protected javax.swing.JButton jButton_Calculate;
    protected javax.swing.JButton jButton_FastForward;
    protected javax.swing.JButton jButton_Next;
    private javax.swing.JButton jButton_OpenFile;
    protected javax.swing.JButton jButton_Previous;
    protected javax.swing.JButton jButton_Rewind;
    protected javax.swing.JLabel jLabelStatusBody;
    private javax.swing.JLabel jLabelStatusHeader;
    protected javax.swing.JLabel jLabel_GameID;
    private javax.swing.JLabel jLabel_GamesFound;
    protected javax.swing.JLabel jLabel_PlyCount;
    protected javax.swing.JList jList_GamesList;
    private javax.swing.JPanel jPanelCalculator;
    private javax.swing.JPanel jPanelGameViewer;
    private javax.swing.JPanel jPanelParser;
    protected javax.swing.JProgressBar jProgressBar_Parser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    protected javax.swing.JTable jTable_Calculator;
    private javax.swing.JTextField jTextField_PGNLocation;
    // End of variables declaration//GEN-END:variables
}
